http:
  routers:
    traefik:
      rule: "Host(`traefik.homeserver.internal`)"
      service: "api@internal"
      tls:
        domains:
          - main: "homeserver.internal"
            sans:
              - "*.homeserver.internal"
              