services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.7.1
    container_name: mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M 
    volumes:
      - /var/docker/mealie:/app/data/
    networks:
      - traefik_proxy
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.http.routers.mealie.rule=Host(`${MEALIE_URL}`)"
      - homepage.group=Cloud & Storage
      - homepage.name=Mealie
      - homepage.icon=mealie.svg
      - homepage.href=https://${MEALIE_URL}
      - homepage.description=Food recipe management

networks:
  traefik_proxy:
    external: true
