services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.3.0
    container_name: mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M 
    volumes:
      - /var/docker/mealie:/app/data/
    networks:
      - traefik_proxy
    environment:
      PUID: 1000
      PGID: 1000
    labels:
      traefik.enable: true
      traefik.http.services.mealie.loadbalancer.server.port: 9000
      traefik.http.routers.mealie.entrypoints: websecure
      traefik.http.routers.mealie.tls: true
      homepage.group: Cloud & Storage
      homepage.name: Mealie
      homepage.icon: mealie.svg
      homepage.href: https://${MEALIE_URL}
      homepage.description: Food recipe management

networks:
  traefik_proxy:
    external: true
