version: '3.8'
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.7
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`${DASHBOARD_URL}`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/heimdall/config:/config
    restart: never
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true