version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.23.0
    container_name: filebrowser
    restart: unless-stopped
    user: 1000:1000
    networks:
      - traefik_proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${FILEBROWSER_DATA}:/data
      - ${FILEBROWSER_DATA2}:/media
      - ./filebrowser.db:/database.db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_URL}`)"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      - "homepage.group=Cloud & Storage"
      - "homepage.name=FileBrowser"
      - "homepage.icon=filebrowser.svg"
      - "homepage.href=https://${FILEBROWSER_URL}"
      - homepage.description=Simple cloud storage access

networks:
  traefik_proxy:
    external: true
