services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.137.3
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/data
      - ${EXTERNAL_LOCATION}:/external
    networks:
      - traefik_proxy
      - immich
    user: 1000:1000
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      disable: false
    labels:
      traefik.enable: true
      traefik.http.routers.immich.tls: true
      traefik.http.routers.immich.entrypoints: websecure
      traefik.http.routers.immich.rule: Host(`${IMMICH_URL}`)
      traefik.http.services.immich.loadbalancer.server.port: 2283
      traefik.docker.network: traefik_proxy
      homepage.group: Cloud & Storage
      homepage.name: Immich
      homepage.icon: immich.svg
      homepage.href: https://${IMMICH_URL}
      homepage.description: Photo & video management

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v1.137.3
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: unless-stopped
    env_file:
      - .env
    depends_on: 
      - immich-server
    networks:
      - immich
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # DB_STORAGE_TYPE: 'HDD' # Explicitly set the storage type if your database isn't stored on SSDs
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - immich
    restart: unless-stopped

volumes:
  model-cache:
networks:
  traefik_proxy:
    external: true
  immich:
