services:
  kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime
    volumes:
      - /var/docker/kuma/data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.entrypoints=websecure"
      - "traefik.http.routers.kuma.tls=true"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
      - homepage.group=Monitoring & Management
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma.svg
      - homepage.href=https://${KUMA_URL}
      - homepage.description=Service uptime monitoring
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
