services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy_kuma
    environment:
        - CONTAINERS=1 # Allow access to viewing containers
    networks:
      - default
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime
    depends_on:
      - dockerproxy
    volumes:
      - /var/docker/kuma/data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - traefik_proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.entrypoints=websecure"
      - "traefik.http.routers.kuma.tls=true"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
      - homepage.group=Monitoring & Management
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma.svg
      - homepage.href=https://${KUMA_URL}
      - homepage.description=Service uptime monitoring
      - homepage.showStats=false
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=https://${KUMA_URL}
      - homepage.widget.slug=${KUMA_SLUG}

networks:
  traefik_proxy:
    external: true
