---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/docker/

my-docker:
  host: dockerproxy_homepage
  port: 2375

# my-docker:
#   socket: /var/run/docker.sock
