---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- logo:
    icon: mdi-home

- resources:
    label: System 
    memory: true
    cpu: true
    cputemp: true
    tempmin: 20
    tempmax: 100
    units: metric
    uptime: true
    disk: /
    
- resources:
    label: Storage
    disk:
        - /mnt/data
        - /mnt/media

# - search:
#     provider: duckduckgo
#     target: _blank
#     showSearchSuggestions: true

- datetime:
    locale: de
    text_size: xl
    format:
      timeStyle: short

- openmeteo:
    label: {{HOMEPAGE_VAR_WIDGET_WEATHER_LABEL}}
    latitude: {{HOMEPAGE_VAR_WIDGET_WEATHER_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_WIDGET_WEATHER_LONGITUDE}}
    units: metric
    cache: 10
  